version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./html/public:/var/www/html/public
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./html:/var/www/html
    links:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database_name
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
    networks:
      - app-network

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: always
    volumes:
      - ./data:/data
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - app-network
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

networks:
  app-network:
    driver: bridge

volumes:
  database:
